var y=Object.create;var l=Object.defineProperty;var b=Object.getOwnPropertyDescriptor;var k=Object.getOwnPropertyNames;var w=Object.getPrototypeOf,x=Object.prototype.hasOwnProperty;var c=r=>l(r,"__esModule",{value:!0});var _=(r,t)=>{c(r);for(var e in t)l(r,e,{get:t[e],enumerable:!0})},C=(r,t,e)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of k(t))!x.call(r,s)&&s!=="default"&&l(r,s,{get:()=>t[s],enumerable:!(e=b(t,s))||e.enumerable});return r},u=r=>C(c(l(r!=null?y(w(r)):{},"default",r&&r.__esModule&&"default"in r?{get:()=>r.default,enumerable:!0}:{value:r,enumerable:!0})),r);_(exports,{default:()=>Q});var v=u(require("atom"));var j="service-fetch",D="0.1.1",I="Provides the fetch API through a web worker",P=!1,R="./lib/main.js",q="./types",A={build:"node ./tools/build.mjs",clean:"rimraf ./lib",dev:"npm run start","lint:ts":"eslint ./src --ignore-path .gitignore",lint:"npm-run-all lint:*",prepublishOnly:"npm run clean && npm run build",start:"cross-env ESBUILD_WATCH=true node ./tools/build.mjs",test:"echo 'Skipping, no tests specified';exit 0;"},S=["fetch","fetch api","http request","web worker","web workers","xmlhttprequest"],W={type:"git",url:"https://github.com/idleberg/atom-service-fetch"},B="https://atom.io/packages/service-fetch",F={url:"https://github.com/idleberg/atom-service-fetch/issues"},M="MIT",T={atom:">=1.52.0 <2.0.0"},L=["core:loaded-shell-environment"],E={"service-fetch":{description:"Provides the fetch API through a web worker",versions:{"0.1.0":"provideFetch"}}},H={},O={"@atxm/developer-console":"^0.5.0","@types/atom":"^1.40.5","@types/node":"^14.14.43","@typescript-eslint/eslint-plugin":"^4.11.1","@typescript-eslint/parser":"^4.11.1","cron-parser":"^3.5.0","cross-env":"^7.0.3","cross-fetch":"^3.1.4",esbuild:"^0.12.9",eslint:"^7.25.0","eslint-plugin-json":"^2.1.2","hash-wasm":"^4.8.0",husky:">=4 <5",jsonlint:"^1.6.3","lint-staged":"^10.5.3","log-symbols":"^5.0.0","npm-run-all":"^4.1.5",prettier:"^2.2.1","source-map-explorer":"^2.5.1",tslib:"^2.0.3",typescript:"^4.1.3"},U={plugins:["@stylelint/remark-preset"]},z={hooks:{"pre-commit":"lint-staged"}},G={"*.ts":["eslint --cache --fix","prettier --write"]},J={node:"14.17.1",yarn:"1.22.10"},g={name:j,version:D,description:I,private:P,main:R,typings:q,scripts:A,keywords:S,repository:W,homepage:B,bugs:F,license:M,engines:T,activationHooks:L,providedServices:E,dependencies:H,devDependencies:O,remarkConfig:U,husky:z,"lint-staged":G,volta:J};function i(r,t){for(var e=0,s=t.length,n=r.length;e<s;e++,n++)r[n]=t[e];return r}var K=function(){function r(t){t===void 0&&(t={}),this.name=t.name,this.styleSheet=`
      background-color: `+(t.backgroundColor||"darkgrey")+`;
      border-radius: 2px;
      color: `+(t.color||"white")+`;
      line-height: 1.5;
      padding: 1px 4px;
      text-shadow: 0 1px 0px rgba(0, 0, 0, 0.2);
    `}return r.prototype.__console__=function(t){for(var e,s=[],n=1;n<arguments.length;n++)s[n-1]=arguments[n];!(atom==null?void 0:atom.inDevMode())||(s.unshift("%c"+this.name+"%c",this.styleSheet,""),(e=window.console)[t].apply(e,s))},r.prototype.debug=function(){for(var t=[],e=0;e<arguments.length;e++)t[e]=arguments[e];this.__console__.apply(this,i(["debug"],t))},r.prototype.error=function(){for(var t=[],e=0;e<arguments.length;e++)t[e]=arguments[e];this.__console__.apply(this,i(["error"],t))},r.prototype.info=function(){for(var t=[],e=0;e<arguments.length;e++)t[e]=arguments[e];this.__console__.apply(this,i(["info"],t))},r.prototype.log=function(){for(var t=[],e=0;e<arguments.length;e++)t[e]=arguments[e];this.__console__.apply(this,i(["log"],t))},r.prototype.trace=function(){for(var t=[],e=0;e<arguments.length;e++)t[e]=arguments[e];this.__console__.apply(this,i(["trace"],t))},r.prototype.warn=function(){for(var t=[],e=0;e<arguments.length;e++)t[e]=arguments[e];this.__console__.apply(this,i(["warn"],t))},r}(),h=K;var a=new h({name:g.name,backgroundColor:"black",color:"gold"});var m=u(require("path"));var d=new Worker((0,m.resolve)(__dirname,"fetchWorker.js"));function p(r,t,e={}){return new Promise(s=>{a.log("Request",e),d.postMessage({responseType:r,url:t,options:e}),d.onmessage=n=>{a.log("Response",n.data),s(n.data)}})}function N(r,t={}){var s;let e=((s=t==null?void 0:t.headers)==null?void 0:s["Content-Type"])||null;switch(!0){case e==="application/octet-stream":return p("arrayBuffer",r,t);case(e==null?void 0:e.startsWith("text/")):return p("text",r,t);default:return p("json",r,t)}}var f=N;var Q={subscriptions:new v.CompositeDisposable,activate(){a.log("Activating package")},deactivate(){var r;a.log("Deactivating package"),(r=this.subscriptions)==null||r.dispose()},provideFetch(){return a.log("Providing service"),f}};0&&(module.exports={});
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
//# sourceMappingURL=main.js.map
